// <auto-generated />
using System;
using AVideoHost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AVideoHost.Migrations
{
    [DbContext(typeof(VideoContext))]
    [Migration("20181216003504_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AVideoHost.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("TitleDescription");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("AVideoHost.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("TitleId");

                    b.Property<string>("VideoUrl");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("AVideoHost.Models.Video", b =>
                {
                    b.HasOne("AVideoHost.Models.Title", "Title")
                        .WithMany("Items")
                        .HasForeignKey("TitleId");
                });
#pragma warning restore 612, 618
        }
    }
}
